export const villages = [
    
        {
  id: 6,
  name: "Jaipur Rural",
  district: "Jaipur",
  riskLevel: "HIGH",
  hazardType: "Flood",
  priority: "HIGH",
  population: 4200,
  lat: 26.9124,
  lng: 75.7873,
},
{
  id: 7,
  name: "Udaipur Hills",
  district: "Udaipur",
  riskLevel: "MEDIUM",
  hazardType: "Landslide",
  priority: "NORMAL",
  population: 2600,
  lat: 24.5854,
  lng: 73.7125,
},
{
  id: 8,
  name: "Jaisalmer Border",
  district: "Jaisalmer",
  riskLevel: "LOW",
  hazardType: "Flood",
  priority: "NORMAL",
  population: 1800,
  lat: 26.9157,
  lng: 70.9083,
},
{
  id: 9,
  name: "Ahmedabad East",
  district: "Ahmedabad",
  riskLevel: "HIGH",
  hazardType: "Flood",
  priority: "HIGH",
  population: 4800,
  lat: 23.0225,
  lng: 72.5714,
},
{
  id: 10,
  name: "Surat Coastal",
  district: "Surat",
  riskLevel: "CRITICAL",
  hazardType: "Flood",
  priority: "IMMEDIATE",
  population: 6200,
  lat: 21.1702,
  lng: 72.8311,
},
{
  id: 11,
  name: "Mumbai Coast",
  district: "Mumbai",
  riskLevel: "CRITICAL",
  hazardType: "Flood",
  priority: "IMMEDIATE",
  population: 7500,
  lat: 19.0760,
  lng: 72.8777,
},
{
  id: 12,
  name: "Pune Valley",
  district: "Pune",
  riskLevel: "HIGH",
  hazardType: "Landslide",
  priority: "HIGH",
  population: 4100,
  lat: 18.5204,
  lng: 73.8567,
},
{
  id: 13,
  name: "Nagpur Central",
  district: "Nagpur",
  riskLevel: "MEDIUM",
  hazardType: "Flood",
  priority: "NORMAL",
  population: 3300,
  lat: 21.1458,
  lng: 79.0882,
},
{
  id: 14,
  name: "Delhi North",
  district: "Delhi",
  riskLevel: "HIGH",
  hazardType: "Flood",
  priority: "HIGH",
  population: 5500,
  lat: 28.7041,
  lng: 77.1025,
},
{
  id: 15,
  name: "Gurugram Sector",
  district: "Gurugram",
  riskLevel: "LOW",
  hazardType: "Flood",
  priority: "NORMAL",
  population: 2400,
  lat: 28.4595,
  lng: 77.0266,
},
{
  id: 16,
  name: "Lucknow East",
  district: "Lucknow",
  riskLevel: "HIGH",
  hazardType: "Flood",
  priority: "HIGH",
  population: 5000,
  lat: 26.8467,
  lng: 80.9462,
},
{
  id: 17,
  name: "Varanasi Riverbank",
  district: "Varanasi",
  riskLevel: "CRITICAL",
  hazardType: "Flood",
  priority: "IMMEDIATE",
  population: 4700,
  lat: 25.3176,
  lng: 82.9739,
},
{
  id: 18,
  name: "Patna Floodplain",
  district: "Patna",
  riskLevel: "CRITICAL",
  hazardType: "Flood",
  priority: "IMMEDIATE",
  population: 6800,
  lat: 25.5941,
  lng: 85.1376,
},
{
  id: 19,
  name: "Ranchi South",
  district: "Ranchi",
  riskLevel: "MEDIUM",
  hazardType: "Landslide",
  priority: "NORMAL",
  population: 2900,
  lat: 23.3441,
  lng: 85.3096,
},
{
  id: 20,
  name: "Kolkata Delta",
  district: "Kolkata",
  riskLevel: "CRITICAL",
  hazardType: "Flood",
  priority: "IMMEDIATE",
  population: 7200,
  lat: 22.5726,
  lng: 88.3639,
},
{
  id: 21,
  name: "Gangtok Hills",
  district: "Gangtok",
  riskLevel: "HIGH",
  hazardType: "Landslide",
  priority: "HIGH",
  population: 2100,
  lat: 27.3389,
  lng: 88.6065,
},
{
  id: 22,
  name: "Guwahati Valley",
  district: "Guwahati",
  riskLevel: "HIGH",
  hazardType: "Flood",
  priority: "HIGH",
  population: 4300,
  lat: 26.1445,
  lng: 91.7362,
},
{
  id: 23,
  name: "Shillong Ridge",
  district: "Shillong",
  riskLevel: "HIGH",
  hazardType: "Landslide",
  priority: "HIGH",
  population: 2500,
  lat: 25.5788,
  lng: 91.8933,
},
{
  id: 24,
  name: "Bhubaneswar East",
  district: "Bhubaneswar",
  riskLevel: "HIGH",
  hazardType: "Flood",
  priority: "HIGH",
  population: 3800,
  lat: 20.2961,
  lng: 85.8245,
},
{
  id: 25,
  name: "Visakhapatnam Coast",
  district: "Visakhapatnam",
  riskLevel: "CRITICAL",
  hazardType: "Flood",
  priority: "IMMEDIATE",
  population: 6400,
  lat: 17.6868,
  lng: 83.2185,
},
{
  id: 26,
  name: "Hyderabad South",
  district: "Hyderabad",
  riskLevel: "MEDIUM",
  hazardType: "Flood",
  priority: "NORMAL",
  population: 3900,
  lat: 17.3850,
  lng: 78.4867,
},
{
  id: 27,
  name: "Bengaluru Rural",
  district: "Bengaluru",
  riskLevel: "LOW",
  hazardType: "Flood",
  priority: "NORMAL",
  population: 3100,
  lat: 12.9716,
  lng: 77.5946,
},
{
  id: 28,
  name: "Mysuru Hills",
  district: "Mysuru",
  riskLevel: "MEDIUM",
  hazardType: "Landslide",
  priority: "NORMAL",
  population: 2300,
  lat: 12.2958,
  lng: 76.6394,
},
{
  id: 29,
  name: "Chennai Coast",
  district: "Chennai",
  riskLevel: "CRITICAL",
  hazardType: "Flood",
  priority: "IMMEDIATE",
  population: 7000,
  lat: 13.0827,
  lng: 80.2707,
},
{
  id: 30,
  name: "Kochi Backwaters",
  district: "Kochi",
  riskLevel: "HIGH",
  hazardType: "Flood",
  priority: "HIGH",
  population: 4500,
  lat: 9.9312,
  lng: 76.2673,
},

];